### ISSUE TITLE
Error executing index.php

### ISSUE THREAD

**Issue by marlev** [flammy/fsapi-remote#1]
Hello, i get the following error message in browser when accessing index.php (after configured IP and PIN) I got PHP 5.5.2.4. I don't know how to quickly find the line from error message, when the php holds several included files.

```
Deprecated: Assigning the return value of new by reference is deprecated in /Users/marca/github/fsapi-remote/xajax/xajax_core/xajax.inc.php on line 360

Deprecated: Assigning the return value of new by reference is deprecated in /Users/marca/github/fsapi-remote/xajax/xajax_core/xajax.inc.php on line 1305

Fatal error: Class 'xajaxUserFunction' not found in /Users/marca/github/fsapi-remote/xajax/xajax_core/xajax.inc.php on line 1305
```

**Comment by flammy** [comment]
Okay, xajax 0.5 is not php5.5 compatible.

I have to try xajax 0.6 beta or something else, to make it compatible.

I have no php5.5 at the moment.

 You can try to replace the xajax-folder with the beta version.

If you want to try it, you have to replace 3 lines in backend.php since xajax changed the syntax:

find:
/\* declare functions as xajax function*/
$xajax->registerFunction("buttonPress");
$xajax->registerFunction("ListItemPress");
$xajax->registerFunction("refresh");

replace with
/\* declare functions as xajax function*/
$xajax->register(XAJAX_FUNCTION,"buttonPress");
$xajax->register(XAJAX_FUNCTION,"ListItemPress");
$xajax->register(XAJAX_FUNCTION,"refresh");

**Comment by marlev** [comment]
Thanks, i was able to download and replace xajax with beta 0.6 and change the lines you outlines. Then I needed to clone your `fsapi` to copy the files to the empty fsapi directory.
Now I got the local site to start loading and I see te page layout but I'm faced with the following error messeage (browser pop-up) 

```
Error: the xajax Javascript component could not be included. Perhaps the URL is incorrect?
URL: /fsapi-remote/xajax/xajax_js/xajax_js/xajax_core.js
```

![screenshot 2015-07-12 19 01 05](https://cloud.githubusercontent.com/assets/659426/8638867/6483aac2-28c8-11e5-931d-c5fee4f09202.png)

**Comment by flammy** [comment]
There was a bug in the Code at github.

The 0.6 Archive from http://www.xajax-project.org/en/download/ was okay.

I updated the Code for the usage with XAJAX 0.6.

Please let me know if the problems still exist.

**Comment by marlev** [comment]
I removed the repository and re-added the updated repository, changed IP & PIN. When accessing local site i got a `Parse error: parse error in /Users/marca/github/fsapi-remote/backend.php on line 32` in browser. I Cannot find anything obvious wrong on line 32.

**Comment by flammy** [comment]
Above of line 32 are the config variables. Please recheck your variables.

Usualy php offers the reason for the parse error e.g. unexpected XYZ, expecting ABC.

If you dont get it to work, please paste a gist.

**Comment by marlev** [comment]
Oh, newbie mistake. Now i got it up and running.
Thanks, really appreciate it.
