### ISSUE TITLE
Index.php not loading

### ISSUE THREAD

**Issue by metieske** [flammy/fsapi-remote#2]
Hi, 
we bought a device using the fsapi and we think it's very cool to see that someone already started making some cool frontend.

we have installed your project but when we start the page we get this error:
xajax_core.js:145 Uncaught SyntaxError: Unexpected token <

also there's a few bootstrap errors
![screen shot 2015-07-23 at 5 02 01 pm](https://cloud.githubusercontent.com/assets/11176517/8853756/90f5a5a0-315c-11e5-8eb2-343c21a0540a.png)

Keep up the good work!

**Comment by metieske** [comment]
managed to fix the bootstrap errors by manually downloading the bootstrap slider files and creating a plugins folder

**Comment by flammy** [comment]
Hi,

the slider is not fully implemented yet, I will put it into git if it is ready.

I get the xajax error if the radio is not reachable.

Please recheck your host an pin settings.

Is the devices website reachable? Do you have installed php5-curl?

The error occurs because php produces output into the json stream.

This output is usualy caused by not set variables, because of missing results from curl call.

To fix this, I have to implement Error-Handling into the gui.

**Comment by flammy** [comment]
I made a small fix, would you please test again?

**Comment by metieske** [comment]
Thanks for the quick reply. I will check if this works tommorow when i'm back in the office.

**Comment by metieske** [comment]
The page loads just fine now :) Thanks for the fix! :+1: 

The only thing not yet working is the channels but I'm not sure if it's implemented yet.

**Comment by flammy** [comment]
The Channel-List is only available in some radio modes.

The click Event does nothing at the moment, I have not figured out how to select one of the entries.

**Comment by metieske** [comment]
Yes I see :) 
I will be waiting eagerly for the upcoming updates!

Issue closed!
